// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one

INSERT INTO posts(id, created_at, updated_at, title, descrtiption, published_at, url , feed_id)

VALUES($1,$2,$3,$4,$5,$6,$7,$8)

RETURNING id, created_at, updated_at, title,descrtiption,published_at,url,feed_id
`

type CreatePostParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Title        string
	Descrtiption sql.NullString
	PublishedAt  string
	Url          string
	FeedID       uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Descrtiption,
		arg.PublishedAt,
		arg.Url,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Descrtiption,
		&i.PublishedAt,
		&i.Url,
		&i.FeedID,
	)
	return i, err
}
